name: Run test

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    name: test projects
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["9.2.2"]
    steps:
    - uses: actions/checkout@v2
    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}-1
        restore-keys: |
          ${{ runner.os }}-stack-
    - uses: haskell/actions/setup@v1.2.7
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'
    - uses: jorelali/setup-elm@v1
    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies
    - name: Exec test
      run: stack --system-ghc test --no-haddock-deps --pedantic
